Move install action to the new system (and add arguments to it)

diff --git a/dotman b/dotman
--- a/dotman
+++ b/dotman
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+scriptDir=$(dirname "$0")
+
 niy() {
     printf "Not implemented (yet)\n"
     exit
@@ -17,8 +19,12 @@ Actions:
     install     Stows dotfiles from source to target.
         Options:
             -s  Source. Defaults to scripts directory.
+            -p  Package. Defaults to 'dotfiles'.
             -t  Target. Defaults to \$HOME.
+            -c  Conflict directory. Defaults to directory 'conflicts' in scripts directory.
             -r  Restow instead of stowing.
+            -y  Don't ask about conflicts.
+            -f  Don't create files and directories.
     uninstall   Unstows dotfiles from target.
         Options:
             -s  Source. Defaults to scripts directory.
@@ -33,11 +39,64 @@ Actions:
             -m  Skip modules.
             -r  Skip restowing.
 EOF
-exit
+[ $1 = 1 ] && exit 0 || exit 1
 }
 
+# install "$source" "$package" "$target" "$conflictDir" "$method" $ask $create
 install() {
-    niy
+    printf "Checking for stow... "
+    if [ -z "$(command -v stow)" ]; then
+        printf "\nStow is missing. Install it and try again."
+        exit
+    fi
+    printf "OK\n"
+
+    printf "Stowing dotfiles... "
+    while true; do
+        conflicts=$(stow -d "$1" -t "$3" $5 "$2" 2>&1 | awk '/\* existing target is/ {print $NF}')
+        if ! [ -z "$conflicts" ]; then
+            printf "Detected conflicts:\n"
+            for file in $conflicts; do
+                printf "$file "
+            done
+            printf "\nDo you want to fix them by moving the files into $4? [Y/n] \n"
+            [ $6 = 1 ] && read fixConflicts || fixConflicts='y'
+            printf "Resolving conflicts... "
+            if [ "$fixConflicts" != "n" ]; then
+                printf "\n"
+                mkdir -p "$conflictDir"
+                for file in $conflicts; do
+                    printf "Moving $file... "
+                    mv -i "$target/$file" "$conflictDir/$(basename "$file")"
+                    printf "OK\n"
+                done
+            else
+                printf "aborted"
+                break
+            fi
+        else
+            printf "OK\n"
+            break
+        fi
+    done
+
+    # TODO: Move directories that user arleady has
+    if [ $7 = 1 ]; then
+        export XDG_CONFIG_HOME=$HOME/.config
+        export XDG_CACHE_HOME=$HOME/.cache
+        export XDG_DATA_HOME=$HOME/.local/share
+
+        mkdir -p "$XDG_DATA_HOME"/vim/{undo,swap,backup}
+        mkdir -p "$XDG_CACHE_HOME"/less
+        mkdir -p "$XDG_CONFIG_HOME"/android
+        mkdir -p "$XDG_DATA_HOME"/cargo
+        mkdir -p "$XDG_DATA_HOME"/gnupg
+        mkdir -p "$XDG_CONFIG_HOME"/java
+        mkdir -p "$XDG_CONFIG_HOME"/less
+        mkdir -p "$XDG_CONFIG_HOME"/npm
+        mkdir -p "$XDG_DATA_HOME"/rustup
+        mkdir -p "$XDG_DATA_HOME"/gradle
+    fi
 }
 
 uninstall() {
@@ -60,16 +119,36 @@ case "$action" in
         help
         ;;
     install)
-        while getopts ':s:t:r' opt; do
+        source="$scriptDir"
+        package="dotfiles"
+        target="$HOME"
+        conflictDir="$scriptDir/conflicts"
+        method='-S'
+        ask=1
+        create=1
+
+        while getopts ':s:p:t:c:ryf' opt; do
             case "${opt}" in
                 s)
                     source="${OPTARG}"
                     ;;
+                p)
+                    package="${OPTARG}"
+                    ;;
                 t)
                     target="${OPTARG}"
                     ;;
+                c)
+                    conflictDir="${OPTARG}"
+                    ;;
                 r)
-                    restow=1
+                    method='-R'
+                    ;;
+                y)
+                    ask=0
+                    ;;
+                f)
+                    create=0
                     ;;
                 *)
                     help
@@ -77,7 +156,7 @@ case "$action" in
                     ;;
             esac
         done
-        install
+        install "$source" "$package" "$target" "$conflictDir" "$method" $ask $create
         ;;
     uninstall)
         while getopts ':s:t:' opt; do
@@ -131,62 +210,6 @@ case "$action" in
         update
         ;;
     *)
-        help
+        help 1
         ;;
 esac
-exit
-
-target="$HOME"
-scriptDir=$(dirname "$0")
-conflictDir="$scriptDir/conflicts"
-
-printf "Checking for stow... "
-if [ -z "$(command -v stow)" ]; then
-    printf "Stow is missing. Install it and try again."
-    exit
-fi
-printf "OK\n"
-
-printf "Stowing dotfiles... "
-while true; do
-    conflicts=$(stow -d "$scriptDir" -t "$target" -S dotfiles 2>&1 | awk '/\* existing target is/ {print $NF}')
-    if ! [ -z "$conflicts" ]; then
-        printf "Detected conflicts:\n"
-        for file in $conflicts; do
-            printf "$file"
-        done
-        printf "\nDo you want to fix them by moving the files into $conflictDir? [Y/n] \n"
-        read fixConflicts
-        printf "Resolving conflicts... "
-        if [ "$fixConflicts" != "n" ]; then
-            printf "\n"
-            mkdir -p "$conflictDir"
-            for file in $conflicts; do
-                printf "Moving $file... "
-                mv -i "$target/$file" "$conflictDir/$(basename "$file")"
-                printf "OK\n"
-            done
-        else
-            printf "aborted"
-            break
-        fi
-    else
-        printf "OK\n"
-        break
-    fi
-done
-
-export XDG_CONFIG_HOME=$HOME/.config
-export XDG_CACHE_HOME=$HOME/.cache
-export XDG_DATA_HOME=$HOME/.local/share
-
-mkdir -p "$XDG_DATA_HOME"/vim/{undo,swap,backup}
-mkdir -p "$XDG_CACHE_HOME"/less
-mkdir -p "$XDG_CONFIG_HOME"/android
-mkdir -p "$XDG_DATA_HOME"/cargo
-mkdir -p "$XDG_DATA_HOME"/gnupg
-mkdir -p "$XDG_CONFIG_HOME"/java
-mkdir -p "$XDG_CONFIG_HOME"/less
-mkdir -p "$XDG_CONFIG_HOME"/npm
-mkdir -p "$XDG_DATA_HOME"/rustup
-mkdir -p "$XDG_DATA_HOME"/gradle
